"""Stage 7: results/paper_vs_ours.md -- every numeric EEG target of the paper
next to the paper pipeline and the released-script pipeline."""
import csv
import sys
from pathlib import Path

import numpy as np
from scipy.stats import wilcoxon

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from eegrepro import data  # noqa: E402

R = data.RESULTS_DIR


def read(name):
    return list(csv.DictReader(open(R / name)))


def erp_acc(rows, contrast, variant, selection="before_cv"):
    return np.array([float(r["accuracy"]) for r in rows if r["contrast"] == contrast
                     and r["variant"] == variant and r["selection"] == selection]) * 100


def fmt(a):
    return f"{a.mean():.1f} ± {a.std(ddof=1):.1f}"


def wg_curve(rows, run):
    acc = np.array([[float(r["accuracy"]) for r in rows if r["run"] == run and r["subject"] == s]
                    for s in data.SUBJECTS]) * 100
    ends = sorted({int(r["window_end_s"]) for r in rows})
    return np.array(ends), acc


def main():
    erp = read("erp_classification.csv")
    wg = read("wg_classification.csv")
    qc = read("qc_preprocess.csv")
    lines = ["# Paper vs reproduction (EEG only)", "",
             "Generated by `scripts/07_report.py`. *Paper pipeline* = the paper's Methods "
             "(1–40 Hz + AAR iWASOBI ocular removal); *released* = the authors' published "
             "MATLAB scripts (no ocular removal). Accuracies are mean ± SD over 26 subjects.", "",
             "## ERP classification (Tables 5 and 6)", "",
             "| Target | Paper | Paper pipeline | Released pipeline | Paper pipeline, intervals nested in CV |",
             "|---|---|---|---|---|"]
    targets = [("DSR: symbol O vs X", "DSR", "86.8 ± 5.9"),
               ("2-back (vs 0-back)", "2-back", "76.9 ± 8.0"),
               ("3-back (vs 0-back)", "3-back", "76.0 ± 7.9"),
               ("2-back target vs non-target", "2-back T/NT", "–"),
               ("3-back target vs non-target", "3-back T/NT", "–")]
    for label, c, paper in targets:
        lines.append(f"| {label} | {paper} | {fmt(erp_acc(erp, c, 'paper'))} | "
                     f"{fmt(erp_acc(erp, c, 'released'))} | {fmt(erp_acc(erp, c, 'paper', 'nested'))} |")
    lines += ["", "2-back vs 3-back accuracy, Wilcoxon signed-rank (paper: P > 0.05):", ""]
    for label, c2 in [("Table 5 contrast", "2-back"), ("target vs non-target", "2-back T/NT")]:
        c3 = c2.replace("2", "3", 1)
        ps = [wilcoxon(erp_acc(erp, c2, v), erp_acc(erp, c3, v)).pvalue for v in ("paper", "released")]
        lines.append(f"- {label}: paper pipeline p = {ps[0]:.3f}, released pipeline p = {ps[1]:.3f}")

    lines += ["", "## WG vs BL EEG classification over time (Fig. 7)", "",
              "| Run | Peak accuracy | Window end at peak | Accuracy at 10 s | Accuracy at 0 s |",
              "|---|---|---|---|---|", "| Paper | 76.9 % | 10 s | 76.9 % | rising before 0 s |"]
    for run, label in [("paper", "Paper pipeline, 10×5 CV"),
                       ("paper_nested_band", "Paper pipeline, band chosen inside CV"),
                       ("released", "Released pipeline, 1×5 CV")]:
        ends, acc = wg_curve(wg, run)
        m = acc.mean(0)
        i = int(np.argmax(m))
        lines.append(f"| {label} | {m[i]:.1f} % | {ends[i]} s | {m[ends == 10][0]:.1f} % | "
                     f"{m[ends == 0][0]:.1f} % |")
    bands = read("wg_bands.csv")
    lo = np.array([float(b["band_lo"]) for b in bands if b["run"] == "paper"])
    hi = np.array([float(b["band_hi"]) for b in bands if b["run"] == "paper"])
    lines += ["", f"Selected CSP bands (paper pipeline): median {np.median(lo):.1f}–{np.median(hi):.1f} Hz, "
              f"lower edge {lo.min():.1f}–{lo.max():.1f} Hz, upper edge {hi.min():.1f}–{hi.max():.1f} Hz."]

    v_b = np.array([float(q["veog_r_before"]) for q in qc])
    v_a = np.array([float(q["veog_r_after"]) for q in qc])
    pr = np.array([float(q["power_ratio"]) for q in qc])
    fb = sum(int(q["fallbacks"]) for q in qc)
    nw = sum(int(q["n_windows"]) for q in qc)
    lines += ["", "## Ocular artifact removal (paper pipeline)", "",
              f"- Mean |r| of frontal channels (Fp1, Fp2, AFz, AFF5h, AFF6h) with VEOG: median "
              f"{np.median(v_b):.2f} before, {np.median(v_a):.2f} after (max after {v_a.max():.2f}).",
              f"- Remaining 1–40 Hz power (all 28 channels): median {np.median(pr):.2f} "
              f"(range {pr.min():.2f}–{pr.max():.2f}).",
              f"- Divergence fallback used in {fb} of {nw} AAR windows.", ""]
    (R / "paper_vs_ours.md").write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
